source "https://rubygems.org"

gem "activerecord", "~> 5.2"
gem "pg", "~> 1.0"
gem "rake"
gem "sinatra", "~> 2.0"
gem "sinatra-activerecord", "~> 2.0.13"
gem "sinatra-contrib"
gem "sinatra-flash"
gem "faker"

group :test, :development do
  gem "pry"
  gem "rspec", "~> 3.7"
  gem "database_cleaner"
  gem "capybara", "~> 2.15"
  gem "shoulda"
  gem "shoulda-matchers", "~> 3.1", require: false
  gem "valid_attribute"
  gem "launchy"
end
