---
title: "Unit Tests and Test-Driven Development"
type: "article"
description: "Describes how to write unit tests for classes using RSpec."
behaviors:
- "ruby_and_rspec"
tags: "tdd, unit-testing, rspec, refactoring"
