---
title: "React Grocery List"
type: "exercise"
description: "Create a Grocery List in React"
tags: "React, stateful components, nested components"
behaviors:
  - react_on_node
ignore:
- "node_modules/"
- "react-notes-stateful.md"
---
